language: c++
sudo: required
dist: trusty
install:
- sudo apt-get update
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo sh -c "echo \"deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse\" >> /etc/apt/sources.list"
- sudo apt-get update
- sudo apt-get install automake autoconf libtool xutils-dev libpciaccess-dev python-mako bison flex libomxil-bellagio-dev libexpat1-dev llvm-dev gcc-4.9 g++-4.9 python3 python3-pip libudev-dev libmtdev-dev mtdev-tools libevdev-dev libx11-xcb-dev libxkbcommon-dev libxrandr-dev x11proto-*-dev libxcb* libxdamage* libx11-xcb-dev libxext-dev libxshmfence-dev libwacom-dev libgtk-3-dev check libpam0g-dev clang-format-3.9 cppcheck/trusty-backports
- ./travisci/check_patch.py
- sudo pip3 install pathlib
- sudo pip3 install meson==0.43.0
- sudo dpkg -s python-mako
- wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip -O /tmp/ninja.zip
- sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 50
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 50
script:
- export LLVM_CONFIG=/usr/bin/llvm-config
- export HWC_BUILD_DIR=/tmp/
- export WLD=/tmp/hwc-install
- export LD_LIBRARY_PATH=$WLD/lib
- export PKG_CONFIG_PATH=$WLD/lib/pkgconfig/:$WLD/lib/x86_64-linux-gnu/pkgconfig:$WLD/share/pkgconfig
- export PATH=$WLD/bin:$PATH
- export ACLOCAL_PATH=$WLD/share/aclocal
- export ACLOCAL="aclocal -I $ACLOCAL_PATH"
- tar -xvf travisci/resources/hwc-install.tar.xz -C $HWC_BUILD_DIR
- mkdir -p $WLD/share/aclocal

#install realpath
- sudo cp $WLD/realpath /usr/bin/

#install ninja
- pushd /tmp
- unzip ninja.zip
- sudo cp ninja /usr/bin/
- popd

#clone and build vaapi : dependency
- pushd /tmp/vaapi
- git clean -xfd > /dev/null
- ./autogen.sh --prefix=$WLD
- make -j5 && make install
- popd
